config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :articles

  devise_for :users

  root 'articles#index'

  resources :users
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true

  def self.search(author)
  if author
    user = User.where(username: author).first
    if user
      self.where(user_id: user.id)
    else
      self.all
    end
  else
    self.all
  end
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :content, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,
    :presence => true,
    :uniqueness => { :case_sensitive => false }

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order(created_at: :desc).paginate(:page => params[:page], :per_page => 5).search(params[:author])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = Comment.where(article_id: params[:id])
    @new_comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { redirect_to(:back)
        flash[:notice] = "Title and content cannot be empty"}
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id, :text_type)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    redirect_to :controller => "articles", :action => "show",
      :id => Comment.find(params[:id]).article_id
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to(:back)
        flash[:notice] = "Comment must have at least 10 characters"}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to(:back) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :article_id, :text_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all.order(:username)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
    end

end

app/helpers/application_helper.rb
require 'kramdown'
module ApplicationHelper
  def markdown_filter(text)
    Kramdown::Document.new(text).to_html.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label' %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label' %>
    <%= f.text_area :content, :class => 'form-control' %>
  </div>
  <div class="form-group" style="display: none">
    <%= f.label :user_id, :class => 'control-label' %>
    <%= f.number_field :user_id, :class => 'form-control', value: current_user.id  %>
  </div>
  <div class="form-group">
    <%= f.label :text_type, :class => 'control-label' %>
    <%= f.select :text_type, options_for_select([['Markdown', 'm'], ['AsciiDoc', 'a']]), include_blank: true %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <table>
    <tr>
      <td>
        <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
      </td>
      <% if user_signed_in? and current_user.author %>
      <td style="padding-left: 30px">
        <%= link_to t('.new', :default => t("helpers.links.new")),
                    new_article_path,
                    :class => 'btn btn-primary' %>
      </td>
      <% end %>
    </tr>
  </table>

</div>



<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

<table class="table table-striped">
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <table class="table table-striped">
          <tbody>
            <tr>
              <td style="font-size: 28px;"><%= link_to article.title, article_path(article) %></td>
            </tr>
            <tr>
              <td>
              <% if article.text_type == "m" %>
                <%= markdown_filter article.content[0..150]+"..." %>
              <% elsif article.text_type == "a" %>
                <%== Asciidoctor.render article.content[0..150]+"..." %>
              <% else %>
                <%= article.content[0..150] %>...
              <% end %>
              </td>
            </tr>
            <tr>
              <td>
                <i>by <%= User.find(article.user_id).username %></i>
                <%= article.created_at.to_s[0..-4] %>

                <% if user_signed_in? %>
                  <% if current_user.admin or current_user.id == article.user_id %>

                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                              edit_article_path(article), :class => 'btn btn-primary btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              article_path(article),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-danger btn-xs' %>
                    <% end %>
                  <% end %>
              </td>

            </tr>


          </tbody>
        </table>
      </tr>
    <% end %>
    <% if user_signed_in? and current_user.author %>
      <table>
      <tr>
        <td>
          <%= link_to t('.new', :default => t("helpers.links.new")),
                      new_article_path,
                      :class => 'btn btn-primary' %>
        </td>
      </tr>
    </table>
    <% end %>
  </tbody>

</table>



<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t @article.title %></h1>
</div>

<table class="">
  <tbody>
    <tr>
      <td>
        <% if @article.text_type == "m" %>
          <%= markdown_filter @article.content %>
        <% elsif @article.text_type == "a" %>
          <%== Asciidoctor.render @article.content %>
        <% else %>
          <td><%= @article.content %></td>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <br>
        <i>by <%= User.find(@article.user_id).username %></i>
      </td>
    </tr>
  </tbody>
</table>
<br>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>

  <% if user_signed_in? and (current_user.admin or current_user.username == @article.user.username) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_article_path(@article), :class => 'btn btn-primary' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                article_path(@article),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>

<br>
<h3>Comments</h3>

<table class="table table-striped">
  <tbody>
    <% @comments.each do |comment| %>
    <tr>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>
              <%= comment.user.username %> at <%= comment.created_at.to_s[0..-4] %> says:
            </td>
          </tr>
          <tr>
            <td>
              <% if comment.text_type == "m" %>
                <%= markdown_filter comment.content %>
              <% elsif comment.text_type == "a" %>
                <%== Asciidoctor.render comment.content %>
              <% else %>
                <%= comment.content %>
              <% end %>
            </td>
          </tr>
          <% if user_signed_in? and current_user.admin %>
            <tr>
              <td style="background: white;">
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            comment_path(comment),
                            :method => 'delete',
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in?%>
<h3>Leave a comment</h3>
  <%= bootstrap_form_for(@new_comment) do |f| %>
    <% if @new_comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@new_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% @new_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <!-- <%= f.label :content %><br> -->
      <%= f.text_area :content, hide_label: true, placeholder: "Your comment..." %>
    </div>
    <div class="field" style="display: none;">
      <!-- <%= f.label :user_id %><br> -->
      <%= f.text_field :user_id, value: current_user.id %>
    </div>
    <div class="field" style="display: none;">
      <!-- <%= f.label :article_id %><br> -->
      <%= f.text_field :article_id, value: @article.id %>
    </div>

    <div class="controls">
      <%= f.select :text_type, options_for_select([['Markdown', 'm'], ['AsciiDoc', 'a']]), include_blank: true %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% end %>

app/views/comments/_form.html.erb
<%= form_for @comment, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label' %>
    <%= f.text_area :content, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <%= f.number_field :user_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :article_id, :class => 'control-label' %>
    <%= f.number_field :article_id, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:article_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.content %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.article_id %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @comment.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @comment.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:article_id) %>:</strong></dt>
  <dd><%= @comment.article_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if flash[:notice] %>
<p class="alert alert-danger" style="padding-left:200px"><%= flash[:notice] %></p>
<% end %>

<!--
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
-->
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= render partial: 'shared/navbar' %>
<div class="container">
  <div class="starter-template">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
          data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        My Blog <span class="glyphicon glyphicon-pencil"></span>
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <% if user_signed_in? and current_user.admin %>
          <li><a href="/users">Users</a></li>
        <% end %>
        <!-- <li><a href="#contact">Contact</a></li> -->
      </ul>

      <%= form_tag articles_path, :method => 'get', :class =>"navbar-form navbar-right", :role => "search" do %>
            <%= (text_field_tag :author, params[:author], class: "form-control", placeholder: "Search by author...") %>

        <%= submit_tag "Search",:category => nil, class:'btn btn-success' %>

      <% end %>

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label' %>
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <%= f.text_field :encrypted_password, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <%= f.text_field :reset_password_token, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <%= f.datetime_select :reset_password_sent_at, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <%= f.datetime_select :remember_created_at, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sign_in_count, :class => 'control-label' %>
    <%= f.number_field :sign_in_count, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <%= f.datetime_select :current_sign_in_at, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <%= f.datetime_select :last_sign_in_at, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <%= f.text_field :current_sign_in_ip, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <%= f.text_field :last_sign_in_ip, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :username, :class => 'control-label' %>
    <%= f.text_field :username, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.last_sign_in_at.to_s[0..-4] %></td>
        <td><%= user.created_at.to_s[0..-5] %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>